# Generated by Django 6.0.4 on 2026-06-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Pago Confirmado'), ('rechazado', 'Pago Rechazado'), ('error', 'Error en Transacción')], default='pendiente', max_length=50)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.matricula')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.metodo_pago')),
            ],
            options={
                'db_table': 'PAG_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TarifaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_lectivo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='academico.curso')),
            ],
            options={
                'db_table': 'PAG_Tarifas_Matricula',
                'managed': True,
                'unique_together': {('curso', 'year_lectivo')},
            },
        ),
    ]
