"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7h8q$z65wb41_=oxg1b5s%tc*z6@njl(6&d!^fsnf9la27*o-1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'usuarios',
    'academico',
    'matriculas',
    'pagos',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

JAZZMIN_SETTINGS = {
    # ── Identidad del sitio ───────────────────────────────────────
    "site_title":    "GestMat",
    "site_header":   "GestMat · Gestión de Matrículas",
    "site_brand":    "🏫 GestMat",
    "welcome_sign":  "Bienvenido al Panel de Administración",
    "copyright":     "Institución Educativa · GestMat",

    # ── Logos / Favicon ───────────────────────────────────────────
    # "site_logo": "img/logo.png",
    # "site_logo_classes": "img-circle",
    # "login_logo": "img/logo.png",

    # ── Búsqueda global ───────────────────────────────────────────
    "search_model": ["usuarios.Usuario", "academico.Estudiante", "matriculas.Matricula"],

    # ── Campo que representa al usuario ───────────────────────────
    "user_avatar": None,

    # ── Menú superior (topmenu) ───────────────────────────────────
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Website", "url": "/", "new_window": True},
        {"model": "usuarios.Usuario"},
        {"model": "academico.estudiante"},
        {"model": "matriculas.matricula"},
    ],

    # ── Menú de usuario (esquina superior derecha) ────────────────
    "usermenu_links": [
        {"model": "usuarios.Usuario"}
    ],

    # ── Barra lateral ─────────────────────────────────────────────
    "show_sidebar":           True,
    "navigation_expanded":    False,
    "hide_apps":              ["auth"],
    "hide_models":            [],

    "custom_links": {
        "usuarios": [{
            "name": "Grupos de Permisos", 
            "url": "admin:auth_group_changelist", 
            "icon": "fas fa-layer-group",
        }]
    },

    # ── Orden personalizado del menú lateral ──────────────────────
    "order_with_respect_to": [
        "usuarios",
        "usuarios.usuario",
        "matriculas",
        "matriculas.matricula",
        "pagos",
        "pagos.pago",
        "pagos.tarifamatricula",
        "academico",
        "auth",
    ],

    # ── Iconos por modelo ─────────────────────────────────────────
    "icons": {
        "usuarios":                 "fas fa-user-shield",
        "usuarios.usuario":         "fas fa-user-shield",
        "academico":                "fas fa-school",
        "academico.estudiante":     "fas fa-user-graduate",
        "academico.acudiente":      "fas fa-users",
        "academico.curso":          "fas fa-chalkboard-teacher",
        "academico.jornada":        "fas fa-clock",
        "academico.eps":            "fas fa-hospital",
        "matriculas":               "fas fa-file-signature",
        "matriculas.matricula":     "fas fa-file-signature",
        "pagos":                    "fas fa-credit-card",
        "pagos.pago":               "fas fa-credit-card",
        "pagos.tarifamatricula":    "fas fa-dollar-sign",
        "pagos.metodo_pago":        "fas fa-money-bill-wave",
        "auth.group":               "fas fa-layer-group",
        "auth.user":                "fas fa-user",
    },

    # ── Icono por defecto ─────────────────────────────────────────
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── Relacionados / extras ─────────────────────────────────────
    "related_modal_active": True,

    # ── Personalización CSS / JS ──────────────────────────────────
    "custom_css": None,
    "custom_js":  None,
    "use_google_fonts_cdn": True,
    "show_ui_builder":      False,    # Poner True temporalmente para ajustar colores
    "custom_css": "css/custom_admin.css",

    # ── Cambio de vista (lista/detalle) ───────────────────────────
    "changeform_format":         "horizontal_tabs",
    "changeform_format_overrides": {
        "usuarios.usuario":   "collapsible",
        "usuarios.matricula": "collapsible",
    },

    # ── Lenguaje / i18n ───────────────────────────────────────────
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
    # Tema general
    "navbar_small_text":         False,
    "footer_small_text":         False,
    "body_small_text":           False,
    "brand_small_text":          False,
    "brand_colour":              "navbar-primary",
    "accent":                    "accent-primary",
    "navbar":                    "navbar-dark",
    "no_navbar_border":          True,
    "navbar_fixed":              True,
    "layout_boxed":              False,
    "footer_fixed":              False,
    "sidebar_fixed":             True,
    "sidebar":                   "sidebar-dark-primary",
    "sidebar_nav_small_text":    False,
    "sidebar_disable_expand":    False,
    "sidebar_nav_child_indent":  True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style":  False,
    "sidebar_nav_flat_style":    False,
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
    "actions_sticky_top": True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "10000/hour",
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_FIELD": "id_usuario",
}



AUTH_USER_MODEL ='usuarios.Usuario'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # <- debe ir de primero
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOWD_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='mssql'),
        'NAME': config('DB_NAME', default='gestmat'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
    }
}

# Solo agregar el puerto si está definido en el .env
db_port = config('DB_PORT', default='')
if db_port:
    DATABASES['default']['PORT'] = db_port

# Configuración específica para SQL Server
if DATABASES['default']['ENGINE'] == 'mssql':
    # Agregamos TrustServerCertificate=yes para evitar errores de handshake SSL local
    extra_params = 'TrustServerCertificate=yes;'
    if config('DB_TRUSTED_CONNECTION', default=False, cast=bool):
        extra_params += 'Trusted_Connection=yes;'
        
    DATABASES['default']['OPTIONS'] = {
        'driver': config('DB_DRIVER', default='ODBC Driver 17 for SQL Server'),
        'extra_params': extra_params,
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = 'C:/fotos_matriculas/'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yanielfer2018@gmail.com'

EMAIL_HOST_PASSWORD = 'mqtm yfij aikv altm'
DEFAULT_FROM_EMAIL = 'yanielfer2018@gmail.com'

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]