# Generated by Django 6.0.4 on 2026-06-21 02:04

import academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acudiente', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'ACA_Acudientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=20, null=True)),
                ('grado', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cupo_total', models.IntegerField(default=30)),
                ('cupo_disponible', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'ACA_Cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'eps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ACA_Estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foto_Acudiente',
            fields=[
                ('id_foto_acudiente', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=academico.models.Ruta_Foto_Acudientes)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ACA_Fotos_Acudientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foto_Estudiante',
            fields=[
                ('id_foto_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=academico.models.Ruta_Foto_Estudiante)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ACA_Fotos_Estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jornadas',
                'managed': True,
            },
        ),
    ]
