# Generated by Django 6.0.4 on 2026-06-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='acudientes',
            field=models.ManyToManyField(blank=True, to='academico.acudiente'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.eps'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento'),
        ),
        migrations.AddField(
            model_name='foto_acudiente',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='academico.acudiente'),
        ),
        migrations.AddField(
            model_name='foto_estudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='academico.estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.jornada'),
        ),
    ]
