from django.contrib import admin
from .models import (
    Acudiente,
    Componente,
    Curso,
    Documento_matricula,
    Eps,
    Estudiante,
    Jornada,
    Matricula,
    Metodo_pago,
    Pagina,
    Pago,
    Perfil,
    Proceso_matricula,
    Seguimiento_matricula,
    Tipo_documento,
    Tipo_documento_matricula,
    Trazabilidad,
    Usuario,
)

admin.site.register(Acudiente)
admin.site.register(Componente)
admin.site.register(Curso)
admin.site.register(Documento_matricula)
admin.site.register(Eps)
admin.site.register(Estudiante)
admin.site.register(Jornada)
admin.site.register(Matricula)
admin.site.register(Metodo_pago)
admin.site.register(Pagina)
admin.site.register(Pago)
admin.site.register(Perfil)
admin.site.register(Proceso_matricula)
admin.site.register(Seguimiento_matricula)
admin.site.register(Tipo_documento)
admin.site.register(Tipo_documento_matricula)
admin.site.register(Trazabilidad)
admin.site.register(Usuario)