# Generated by Django 6.0.4 on 2026-06-07 22:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'eps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jornadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('insert_perfil', models.BooleanField(default=False)),
                ('update_perfil', models.BooleanField(default=False)),
                ('delete_perfil', models.BooleanField(default=False)),
                ('view_perfil', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SEC_Perfiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proceso_matricula',
            fields=[
                ('id_proceso_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_paso', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('obligatorio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
            ],
            options={
                'db_table': 'PRCM_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id_tipo_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento_matricula',
            fields=[
                ('id_tipo_documento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('obligatorio', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tipos_documento_matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('token_reset', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('token_bloqueado', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.permission')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento')),
            ],
            options={
                'db_table': 'SEC_Usuarios',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acudiente', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento')),
            ],
            options={
                'db_table': 'ACA_Acudientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('acudientes', models.ManyToManyField(blank=True, to='usuarios.acudiente')),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.eps')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento')),
            ],
            options={
                'db_table': 'ACA_Estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foto_Acudiente',
            fields=[
                ('id_foto_acudiente', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Acudientes)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.acudiente')),
            ],
            options={
                'db_table': 'ACA_Fotos_Acudientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foto_Estudiante',
            fields=[
                ('id_foto_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Estudiante)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.estudiante')),
            ],
            options={
                'db_table': 'ACA_Fotos_Estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foto_Usuario',
            fields=[
                ('id_foto_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Usuario)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SEC_Fotos_Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=20, null=True)),
                ('grado', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cupo_total', models.IntegerField(default=30)),
                ('cupo_disponible', models.IntegerField(default=30)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.jornada')),
            ],
            options={
                'db_table': 'ACA_Cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('year_lectivo', models.IntegerField()),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('acudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.acudiente')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.curso')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.estudiante')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.jornada')),
            ],
            options={
                'db_table': 'MAT_Matriculas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Pago Confirmado'), ('rechazado', 'Pago Rechazado'), ('error', 'Error en Transacción')], default='pendiente', max_length=50)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.matricula')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.metodo_pago')),
            ],
            options={
                'db_table': 'PAG_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento_matricula',
            fields=[
                ('id_seguimiento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.matricula')),
                ('paso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.proceso_matricula')),
                ('usuario_actualiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MAT_Seguimientos_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento_matricula',
            fields=[
                ('id_documento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revision', 'Revision'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('usuario_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas', to=settings.AUTH_USER_MODEL)),
                ('usuario_revisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.matricula')),
                ('tipo_documento_matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento_matricula')),
            ],
            options={
                'db_table': 'MAT_Documentos_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id_trazabilidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AUD_Trazabilidad',
                'managed': True,
            },
        ),
    ]
