# Generated by Django 6.0.4 on 2026-06-21 02:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('insert_perfil', models.BooleanField(default=False)),
                ('update_perfil', models.BooleanField(default=False)),
                ('delete_perfil', models.BooleanField(default=False)),
                ('view_perfil', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SEC_Perfiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id_tipo_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('token_reset', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('token_bloqueado', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.permission')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipo_documento')),
            ],
            options={
                'db_table': 'SEC_Usuarios',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Usuario',
            fields=[
                ('id_foto_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Usuario)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SEC_Fotos_Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id_trazabilidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AUD_Trazabilidad',
                'managed': True,
            },
        ),
    ]
