# Generated by Django 6.0.4 on 2026-06-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'permissions': [('ver_modulo_matriculas', 'Puede ver el módulo de Matrículas'), ('ver_modulo_pagos', 'Puede ver el módulo de Pagos'), ('ver_modulo_academico', 'Puede ver el módulo Académico'), ('ver_modulo_usuarios', 'Puede ver el módulo de Usuarios'), ('ver_modulo_reportes', 'Puede ver el módulo de Reportes')]},
        ),
    ]
