# Generated by Django 6.0.4 on 2026-06-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'permissions': [('ver_modulo_matriculas', 'Puede ver el módulo de Matrículas'), ('ver_modulo_gestion_academica', 'Puede ver el módulo de Gestión Académica'), ('ver_modulo_administracion', 'Puede ver el módulo de Administración'), ('ver_dashboard_matriculas', 'Puede ver el dashboard de Matrículas')]},
        ),
    ]
