# Generated by Django 6.0.4 on 2026-04-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='view_perfil',
            field=models.BooleanField(default=False),
        ),
    ]
