# Generated by Django 6.0.4 on 2026-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_view_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
