# Generated by Django 6.0.4 on 2026-05-01 22:14

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_eps_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={'verbose_name': 'Acudiente', 'verbose_name_plural': 'Acudientes'},
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='documento_matricula',
            options={'verbose_name': 'Documento de Matrícula', 'verbose_name_plural': 'Documentos de Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'verbose_name': 'EPS', 'verbose_name_plural': 'EPS'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='metodo_pago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='proceso_matricula',
            options={'verbose_name': 'Proceso de Matrícula', 'verbose_name_plural': 'Procesos de Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='seguimiento_matricula',
            options={'verbose_name': 'Seguimiento de Matrícula', 'verbose_name_plural': 'Seguimientos de Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='tipo_documento_matricula',
            options={'verbose_name': 'Tipo de Documento Matrícula', 'verbose_name_plural': 'Tipos de Documentos Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='trazabilidad',
            options={'verbose_name': 'Trazabilidad', 'verbose_name_plural': 'Trazabilidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='acudiente',
            name='foto_acudiente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='foto_estudiante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto_usuario',
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documento_matricula',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revision', 'Revision'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='acudiente',
            table='Acudientes',
        ),
        migrations.AlterModelTable(
            name='componente',
            table='Componentes',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Cursos',
        ),
        migrations.AlterModelTable(
            name='documento_matricula',
            table='Documentos_Matricula',
        ),
        migrations.AlterModelTable(
            name='eps',
            table='Eps',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='Estudiantes',
        ),
        migrations.AlterModelTable(
            name='jornada',
            table='Jornadas',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='Matriculas',
        ),
        migrations.AlterModelTable(
            name='metodo_pago',
            table='Metodos_Pago',
        ),
        migrations.AlterModelTable(
            name='pagina',
            table='Paginas',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='Pagos',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='Perfiles',
        ),
        migrations.AlterModelTable(
            name='proceso_matricula',
            table='Procesos_Matricula',
        ),
        migrations.AlterModelTable(
            name='seguimiento_matricula',
            table='Seguimientos_Matricula',
        ),
        migrations.AlterModelTable(
            name='tipo_documento',
            table='Tipos_Documento',
        ),
        migrations.AlterModelTable(
            name='tipo_documento_matricula',
            table='Tipos_Documento_Matricula',
        ),
        migrations.AlterModelTable(
            name='trazabilidad',
            table='Trazabilidad',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
        migrations.CreateModel(
            name='Foto_Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Acudientes)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.acudiente')),
            ],
            options={
                'verbose_name': 'Foto de Acudiente',
                'verbose_name_plural': 'Fotos de Acudientes',
                'db_table': 'Fotos_Acudientes',
            },
        ),
        migrations.CreateModel(
            name='Foto_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Estudiante)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.estudiante')),
            ],
            options={
                'verbose_name': 'Foto de Estudiante',
                'verbose_name_plural': 'Fotos de Estudiantes',
                'db_table': 'Fotos_Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Foto_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=usuarios.models.Ruta_Foto_Usuario)),
                ('ruta_disco', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Usuario',
                'verbose_name_plural': 'Fotos de Usuarios',
                'db_table': 'Fotos_Usuarios',
            },
        ),
    ]
