# Generated by Django 6.0.4 on 2026-05-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_acudiente_options_alter_componente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acudiente',
            table='acudientes',
        ),
        migrations.AlterModelTable(
            name='componente',
            table='componentes',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
        migrations.AlterModelTable(
            name='documento_matricula',
            table='documentos_matricula',
        ),
        migrations.AlterModelTable(
            name='eps',
            table='eps',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiantes',
        ),
        migrations.AlterModelTable(
            name='foto_acudiente',
            table='fotos_acudientes',
        ),
        migrations.AlterModelTable(
            name='foto_estudiante',
            table='fotos_estudiantes',
        ),
        migrations.AlterModelTable(
            name='foto_usuario',
            table='fotos_usuarios',
        ),
        migrations.AlterModelTable(
            name='jornada',
            table='jornadas',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matriculas',
        ),
        migrations.AlterModelTable(
            name='metodo_pago',
            table='metodos_pago',
        ),
        migrations.AlterModelTable(
            name='pagina',
            table='paginas',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pagos',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfiles',
        ),
        migrations.AlterModelTable(
            name='proceso_matricula',
            table='procesos_matricula',
        ),
        migrations.AlterModelTable(
            name='seguimiento_matricula',
            table='seguimientos_matricula',
        ),
        migrations.AlterModelTable(
            name='tipo_documento',
            table='tipos_documento',
        ),
        migrations.AlterModelTable(
            name='tipo_documento_matricula',
            table='tipos_documento_matricula',
        ),
        migrations.AlterModelTable(
            name='trazabilidad',
            table='trazabilidad',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
