# Generated by Django 6.0.4 on 2026-05-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_acudiente_table_alter_componente_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
