# Generated by Django 6.0.4 on 2026-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfil_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_documento',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
