# Generated by Django 6.0.4 on 2026-06-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_matricula',
            fields=[
                ('id_documento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revision', 'Revision'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MAT_Documentos_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('year_lectivo', models.IntegerField()),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MAT_Matriculas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proceso_matricula',
            fields=[
                ('id_proceso_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_paso', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('obligatorio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
            ],
            options={
                'db_table': 'PRCM_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento_matricula',
            fields=[
                ('id_seguimiento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MAT_Seguimientos_Matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento_matricula',
            fields=[
                ('id_tipo_documento_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('obligatorio', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tipos_documento_matricula',
                'managed': True,
            },
        ),
    ]
