# Generated by Django 6.0.4 on 2026-06-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento_matricula',
            name='usuario_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento_matricula',
            name='usuario_revisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='acudiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.acudiente'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.jornada'),
        ),
        migrations.AddField(
            model_name='documento_matricula',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.matricula'),
        ),
        migrations.AddField(
            model_name='seguimiento_matricula',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.matricula'),
        ),
        migrations.AddField(
            model_name='seguimiento_matricula',
            name='paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.proceso_matricula'),
        ),
        migrations.AddField(
            model_name='seguimiento_matricula',
            name='usuario_actualiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento_matricula',
            name='tipo_documento_matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.tipo_documento_matricula'),
        ),
    ]
