# Generated by Django 6.0.4 on 2026-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMesIngreso',
            fields=[
                ('id_config', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('year_lectivo', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración Mes de Ingreso',
                'verbose_name_plural': 'Configuraciones Meses de Ingreso',
                'db_table': 'MAT_Configuracion_Mes_Ingreso',
                'managed': True,
                'unique_together': {('mes', 'year_lectivo')},
            },
        ),
    ]
